# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Model1Request = channel.unary_unary(
                '/message.Greeter/Model1Request',
                request_serializer=message__pb2.Model1RequestMessage.SerializeToString,
                response_deserializer=message__pb2.Model1ResponseMessage.FromString,
                )
        self.Model2Request = channel.unary_unary(
                '/message.Greeter/Model2Request',
                request_serializer=message__pb2.Model2RequestMessage.SerializeToString,
                response_deserializer=message__pb2.Model2ResponseMessage.FromString,
                )
        self.Model3Request = channel.unary_unary(
                '/message.Greeter/Model3Request',
                request_serializer=message__pb2.Model3RequestMessage.SerializeToString,
                response_deserializer=message__pb2.Model3ResponseMessage.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Model1Request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Model2Request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Model3Request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Model1Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Model1Request,
                    request_deserializer=message__pb2.Model1RequestMessage.FromString,
                    response_serializer=message__pb2.Model1ResponseMessage.SerializeToString,
            ),
            'Model2Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Model2Request,
                    request_deserializer=message__pb2.Model2RequestMessage.FromString,
                    response_serializer=message__pb2.Model2ResponseMessage.SerializeToString,
            ),
            'Model3Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Model3Request,
                    request_deserializer=message__pb2.Model3RequestMessage.FromString,
                    response_serializer=message__pb2.Model3ResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Model1Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.Greeter/Model1Request',
            message__pb2.Model1RequestMessage.SerializeToString,
            message__pb2.Model1ResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Model2Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.Greeter/Model2Request',
            message__pb2.Model2RequestMessage.SerializeToString,
            message__pb2.Model2ResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Model3Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.Greeter/Model3Request',
            message__pb2.Model3RequestMessage.SerializeToString,
            message__pb2.Model3ResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
