# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07message\"K\n\x14Model1RequestMessage\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\"g\n\x15Model1ResponseMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08model_id\x18\x05 \x01(\t\"T\n\x14Model2RequestMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x10\n\x08model_id\x18\x04 \x01(\t\"U\n\x15Model2ResponseMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x10\n\x08model_id\x18\x04 \x01(\t\"C\n\x14Model3RequestMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\"D\n\x15Model3ResponseMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t2\xff\x01\n\x07Greeter\x12P\n\rModel1Request\x12\x1d.message.Model1RequestMessage\x1a\x1e.message.Model1ResponseMessage\"\x00\x12P\n\rModel2Request\x12\x1d.message.Model2RequestMessage\x1a\x1e.message.Model2ResponseMessage\"\x00\x12P\n\rModel3Request\x12\x1d.message.Model3RequestMessage\x1a\x1e.message.Model3ResponseMessage\"\x00\x62\x06proto3')



_MODEL1REQUESTMESSAGE = DESCRIPTOR.message_types_by_name['Model1RequestMessage']
_MODEL1RESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['Model1ResponseMessage']
_MODEL2REQUESTMESSAGE = DESCRIPTOR.message_types_by_name['Model2RequestMessage']
_MODEL2RESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['Model2ResponseMessage']
_MODEL3REQUESTMESSAGE = DESCRIPTOR.message_types_by_name['Model3RequestMessage']
_MODEL3RESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['Model3ResponseMessage']
Model1RequestMessage = _reflection.GeneratedProtocolMessageType('Model1RequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _MODEL1REQUESTMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Model1RequestMessage)
  })
_sym_db.RegisterMessage(Model1RequestMessage)

Model1ResponseMessage = _reflection.GeneratedProtocolMessageType('Model1ResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _MODEL1RESPONSEMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Model1ResponseMessage)
  })
_sym_db.RegisterMessage(Model1ResponseMessage)

Model2RequestMessage = _reflection.GeneratedProtocolMessageType('Model2RequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _MODEL2REQUESTMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Model2RequestMessage)
  })
_sym_db.RegisterMessage(Model2RequestMessage)

Model2ResponseMessage = _reflection.GeneratedProtocolMessageType('Model2ResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _MODEL2RESPONSEMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Model2ResponseMessage)
  })
_sym_db.RegisterMessage(Model2ResponseMessage)

Model3RequestMessage = _reflection.GeneratedProtocolMessageType('Model3RequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _MODEL3REQUESTMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Model3RequestMessage)
  })
_sym_db.RegisterMessage(Model3RequestMessage)

Model3ResponseMessage = _reflection.GeneratedProtocolMessageType('Model3ResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _MODEL3RESPONSEMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Model3ResponseMessage)
  })
_sym_db.RegisterMessage(Model3ResponseMessage)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODEL1REQUESTMESSAGE._serialized_start=26
  _MODEL1REQUESTMESSAGE._serialized_end=101
  _MODEL1RESPONSEMESSAGE._serialized_start=103
  _MODEL1RESPONSEMESSAGE._serialized_end=206
  _MODEL2REQUESTMESSAGE._serialized_start=208
  _MODEL2REQUESTMESSAGE._serialized_end=292
  _MODEL2RESPONSEMESSAGE._serialized_start=294
  _MODEL2RESPONSEMESSAGE._serialized_end=379
  _MODEL3REQUESTMESSAGE._serialized_start=381
  _MODEL3REQUESTMESSAGE._serialized_end=448
  _MODEL3RESPONSEMESSAGE._serialized_start=450
  _MODEL3RESPONSEMESSAGE._serialized_end=518
  _GREETER._serialized_start=521
  _GREETER._serialized_end=776
# @@protoc_insertion_point(module_scope)
