# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06vision\"p\n\x15\x46\x61\x63\x65\x43ollectionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08pull_url\x18\x04 \x01(\t\x12\x10\n\x08push_url\x18\x05 \x01(\t\"G\n\x10RemoveUrlRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\"/\n\x0e\x43ommonResopnse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"c\n\x18StartVisonServiceRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\x10\n\x08pull_url\x18\x02 \x01(\t\x12\x10\n\x08push_url\x18\x03 \x01(\t\x12\x10\n\x08model_id\x18\x04 \x01(\x05\x32\xe6\x01\n\rVisionService\x12G\n\x0e\x46\x61\x63\x65\x43ollection\x12\x1d.vision.FaceCollectionRequest\x1a\x16.vision.CommonResopnse\x12=\n\tRemoveUrl\x12\x18.vision.RemoveUrlRequest\x1a\x16.vision.CommonResopnse\x12M\n\x11StartVisonService\x12 .vision.StartVisonServiceRequest\x1a\x16.vision.CommonResopnseB=\n)com.example.ex3_2_back.grpc.server.visionB\x0bVisionProtoP\x01\x88\x01\x01\x62\x06proto3')



_FACECOLLECTIONREQUEST = DESCRIPTOR.message_types_by_name['FaceCollectionRequest']
_REMOVEURLREQUEST = DESCRIPTOR.message_types_by_name['RemoveUrlRequest']
_COMMONRESOPNSE = DESCRIPTOR.message_types_by_name['CommonResopnse']
_STARTVISONSERVICEREQUEST = DESCRIPTOR.message_types_by_name['StartVisonServiceRequest']
FaceCollectionRequest = _reflection.GeneratedProtocolMessageType('FaceCollectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACECOLLECTIONREQUEST,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:vision.FaceCollectionRequest)
  })
_sym_db.RegisterMessage(FaceCollectionRequest)

RemoveUrlRequest = _reflection.GeneratedProtocolMessageType('RemoveUrlRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEURLREQUEST,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:vision.RemoveUrlRequest)
  })
_sym_db.RegisterMessage(RemoveUrlRequest)

CommonResopnse = _reflection.GeneratedProtocolMessageType('CommonResopnse', (_message.Message,), {
  'DESCRIPTOR' : _COMMONRESOPNSE,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:vision.CommonResopnse)
  })
_sym_db.RegisterMessage(CommonResopnse)

StartVisonServiceRequest = _reflection.GeneratedProtocolMessageType('StartVisonServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTVISONSERVICEREQUEST,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:vision.StartVisonServiceRequest)
  })
_sym_db.RegisterMessage(StartVisonServiceRequest)

_VISIONSERVICE = DESCRIPTOR.services_by_name['VisionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.example.ex3_2_back.grpc.server.visionB\013VisionProtoP\001\210\001\001'
  _FACECOLLECTIONREQUEST._serialized_start=24
  _FACECOLLECTIONREQUEST._serialized_end=136
  _REMOVEURLREQUEST._serialized_start=138
  _REMOVEURLREQUEST._serialized_end=209
  _COMMONRESOPNSE._serialized_start=211
  _COMMONRESOPNSE._serialized_end=258
  _STARTVISONSERVICEREQUEST._serialized_start=260
  _STARTVISONSERVICEREQUEST._serialized_end=359
  _VISIONSERVICE._serialized_start=362
  _VISIONSERVICE._serialized_end=592
# @@protoc_insertion_point(module_scope)
