# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05\x65vent\"B\n\x13\x45ventServerResopnse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"C\n\x1c\x45motionDetectionEventRequest\x12\x11\n\telderlyId\x18\x01 \x01(\x05\x12\x10\n\x08imageUrl\x18\x02 \x01(\t\"\\\n VolunteerInteractionEventRequest\x12\x11\n\telderlyId\x18\x01 \x01(\x05\x12\x13\n\x0bvolunteerId\x18\x02 \x01(\x05\x12\x10\n\x08imageUrl\x18\x03 \x01(\t\"1\n\x1dStrangerDetectionEventRequest\x12\x10\n\x08imageUrl\x18\x01 \x01(\t\"-\n\x19\x46\x61llDetectionEventRequest\x12\x10\n\x08imageUrl\x18\x01 \x01(\t\">\n*ForbiddenAreaInvasionDetectionEventRequest\x12\x10\n\x08imageUrl\x18\x01 \x01(\t2\xf0\x03\n\x0c\x45ventService\x12X\n\x15\x45motionDetectionEvent\x12#.event.EmotionDetectionEventRequest\x1a\x1a.event.EventServerResopnse\x12`\n\x19VolunteerInteractionEvent\x12\'.event.VolunteerInteractionEventRequest\x1a\x1a.event.EventServerResopnse\x12Z\n\x16StrangerDetectionEvent\x12$.event.StrangerDetectionEventRequest\x1a\x1a.event.EventServerResopnse\x12R\n\x12\x46\x61llDetectionEvent\x12 .event.FallDetectionEventRequest\x1a\x1a.event.EventServerResopnse\x12t\n#ForbiddenAreaInvasionDetectionEvent\x12\x31.event.ForbiddenAreaInvasionDetectionEventRequest\x1a\x1a.event.EventServerResopnseBB\n(com.example.ex3_2_back.grpc.server.eventB\x11\x45ventServiceProtoP\x01\x88\x01\x01\x62\x06proto3')



_EVENTSERVERRESOPNSE = DESCRIPTOR.message_types_by_name['EventServerResopnse']
_EMOTIONDETECTIONEVENTREQUEST = DESCRIPTOR.message_types_by_name['EmotionDetectionEventRequest']
_VOLUNTEERINTERACTIONEVENTREQUEST = DESCRIPTOR.message_types_by_name['VolunteerInteractionEventRequest']
_STRANGERDETECTIONEVENTREQUEST = DESCRIPTOR.message_types_by_name['StrangerDetectionEventRequest']
_FALLDETECTIONEVENTREQUEST = DESCRIPTOR.message_types_by_name['FallDetectionEventRequest']
_FORBIDDENAREAINVASIONDETECTIONEVENTREQUEST = DESCRIPTOR.message_types_by_name['ForbiddenAreaInvasionDetectionEventRequest']
EventServerResopnse = _reflection.GeneratedProtocolMessageType('EventServerResopnse', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSERVERRESOPNSE,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.EventServerResopnse)
  })
_sym_db.RegisterMessage(EventServerResopnse)

EmotionDetectionEventRequest = _reflection.GeneratedProtocolMessageType('EmotionDetectionEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMOTIONDETECTIONEVENTREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.EmotionDetectionEventRequest)
  })
_sym_db.RegisterMessage(EmotionDetectionEventRequest)

VolunteerInteractionEventRequest = _reflection.GeneratedProtocolMessageType('VolunteerInteractionEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOLUNTEERINTERACTIONEVENTREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.VolunteerInteractionEventRequest)
  })
_sym_db.RegisterMessage(VolunteerInteractionEventRequest)

StrangerDetectionEventRequest = _reflection.GeneratedProtocolMessageType('StrangerDetectionEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _STRANGERDETECTIONEVENTREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.StrangerDetectionEventRequest)
  })
_sym_db.RegisterMessage(StrangerDetectionEventRequest)

FallDetectionEventRequest = _reflection.GeneratedProtocolMessageType('FallDetectionEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _FALLDETECTIONEVENTREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.FallDetectionEventRequest)
  })
_sym_db.RegisterMessage(FallDetectionEventRequest)

ForbiddenAreaInvasionDetectionEventRequest = _reflection.GeneratedProtocolMessageType('ForbiddenAreaInvasionDetectionEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _FORBIDDENAREAINVASIONDETECTIONEVENTREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.ForbiddenAreaInvasionDetectionEventRequest)
  })
_sym_db.RegisterMessage(ForbiddenAreaInvasionDetectionEventRequest)

_EVENTSERVICE = DESCRIPTOR.services_by_name['EventService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n(com.example.ex3_2_back.grpc.server.eventB\021EventServiceProtoP\001\210\001\001'
  _EVENTSERVERRESOPNSE._serialized_start=22
  _EVENTSERVERRESOPNSE._serialized_end=88
  _EMOTIONDETECTIONEVENTREQUEST._serialized_start=90
  _EMOTIONDETECTIONEVENTREQUEST._serialized_end=157
  _VOLUNTEERINTERACTIONEVENTREQUEST._serialized_start=159
  _VOLUNTEERINTERACTIONEVENTREQUEST._serialized_end=251
  _STRANGERDETECTIONEVENTREQUEST._serialized_start=253
  _STRANGERDETECTIONEVENTREQUEST._serialized_end=302
  _FALLDETECTIONEVENTREQUEST._serialized_start=304
  _FALLDETECTIONEVENTREQUEST._serialized_end=349
  _FORBIDDENAREAINVASIONDETECTIONEVENTREQUEST._serialized_start=351
  _FORBIDDENAREAINVASIONDETECTIONEVENTREQUEST._serialized_end=413
  _EVENTSERVICE._serialized_start=416
  _EVENTSERVICE._serialized_end=912
# @@protoc_insertion_point(module_scope)
